### ISSUE TITLE
Not overwrite if key exists

### ISSUE THREAD

**Issue by ezeq-10** [petreboy14/redis-scheduler#9]
Hi, 
Congrats for you library, is very useful.
Probably i've found an issue, actually it doesn't checks if key already exists, you are setting like this
`this.clients.scheduler.set(options.key, '', 'PX', this.getMillis(options.expire), cb);`
I created a list on redis, and when I tried to schedule it, the key was overwritten and appears empty and casted as String.
So, I'll send you a PR with a little change to fix this, Thanks!

**Comment by petreboy14** [comment]
Thanks @ezeq-10.  I fixed a couple `this` references that needed to be `self` but it's merged and published on npm to version 0.11.2
